### ISSUE TITLE
[minor] Validation of cidr in command line

### ISSUE THREAD

**Issue by dougbtv** [s1061123/koro#1]
Hey Tomo, this is extremely minor, but, figured I'd report it... If you don't remember to have a valid cidr in the koro command line arguments, it give this error:

```
[root@koko1 centos]# ./koro docker test1 address add 10.0.1.1 dev link1

docker test1 address add 10.0.1.1 dev link1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error
failed to get container info: EOFerr:failed to get container info: EOF
```

naturally, it works properly if you have the `/24` in there, e.g.

```
[root@koko1 centos]# ./koro docker test1 address add 10.0.1.1/24 dev link1
Succeed!
```

No rush to fix, but, something maybe to validate.

**Comment by s1061123** [comment]
Hi Doug, thank you for your report!
6119238e3ed629d8f9d0f76c589be0989454586f adds parse error with messsage, so it could be taken care of following examples.

```
[root@koko1 centos]# ./koro docker test1 address add 10.0.1.1 dev link1

docker test1 address add 10.0.1.1 dev link1
                         ~~~~~~~~~~~~~~~~~~
Parse error: Invalid address
Parse failed!
```

`ip` command  (iproute2) sometimes regards address without prefixlen (e.g. '/24') as host address ('/32'), however, `koro` does not have a plan to implement it due to avoid configuration error.

Comments and additional fix proposals are welcome.

**Comment by dougbtv** [comment]
Awesome! That fix looks perfect, thanks a bunch, too.
